// <auto-generated />
using CBakiWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CBakiWebsite.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20251027061552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CBakiWebsite.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CD")
                        .HasColumnType("int");

                    b.Property<float>("Damage")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("CBakiWebsite.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BMove1Id")
                        .HasColumnType("int");

                    b.Property<int?>("BMove2Id")
                        .HasColumnType("int");

                    b.Property<int?>("BMove3Id")
                        .HasColumnType("int");

                    b.Property<int?>("BMove4Id")
                        .HasColumnType("int");

                    b.Property<int?>("BMove5Id")
                        .HasColumnType("int");

                    b.Property<int?>("CMove1Id")
                        .HasColumnType("int");

                    b.Property<int?>("CMove2Id")
                        .HasColumnType("int");

                    b.Property<int?>("CMove3Id")
                        .HasColumnType("int");

                    b.Property<int?>("CMove4Id")
                        .HasColumnType("int");

                    b.Property<int?>("CMove5Id")
                        .HasColumnType("int");

                    b.Property<int>("MinAgility")
                        .HasColumnType("int");

                    b.Property<int>("MinDurability")
                        .HasColumnType("int");

                    b.Property<int>("MinIntellect")
                        .HasColumnType("int");

                    b.Property<int>("MinStrength")
                        .HasColumnType("int");

                    b.Property<int?>("MiscMove1Id")
                        .HasColumnType("int");

                    b.Property<int?>("MiscMove2Id")
                        .HasColumnType("int");

                    b.Property<int?>("MiscMove3Id")
                        .HasColumnType("int");

                    b.Property<int?>("MiscMove4Id")
                        .HasColumnType("int");

                    b.Property<int?>("MiscMove5Id")
                        .HasColumnType("int");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VMove1Id")
                        .HasColumnType("int");

                    b.Property<int?>("VMove2Id")
                        .HasColumnType("int");

                    b.Property<int?>("VMove3Id")
                        .HasColumnType("int");

                    b.Property<int?>("VMove4Id")
                        .HasColumnType("int");

                    b.Property<int?>("VMove5Id")
                        .HasColumnType("int");

                    b.Property<int?>("XMove1Id")
                        .HasColumnType("int");

                    b.Property<int?>("XMove2Id")
                        .HasColumnType("int");

                    b.Property<int?>("XMove3Id")
                        .HasColumnType("int");

                    b.Property<int?>("XMove4Id")
                        .HasColumnType("int");

                    b.Property<int?>("XMove5Id")
                        .HasColumnType("int");

                    b.Property<int?>("ZMove1Id")
                        .HasColumnType("int");

                    b.Property<int?>("ZMove2Id")
                        .HasColumnType("int");

                    b.Property<int?>("ZMove3Id")
                        .HasColumnType("int");

                    b.Property<int?>("ZMove4Id")
                        .HasColumnType("int");

                    b.Property<int?>("ZMove5Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BMove1Id");

                    b.HasIndex("BMove2Id");

                    b.HasIndex("BMove3Id");

                    b.HasIndex("BMove4Id");

                    b.HasIndex("BMove5Id");

                    b.HasIndex("CMove1Id");

                    b.HasIndex("CMove2Id");

                    b.HasIndex("CMove3Id");

                    b.HasIndex("CMove4Id");

                    b.HasIndex("CMove5Id");

                    b.HasIndex("MiscMove1Id");

                    b.HasIndex("MiscMove2Id");

                    b.HasIndex("MiscMove3Id");

                    b.HasIndex("MiscMove4Id");

                    b.HasIndex("MiscMove5Id");

                    b.HasIndex("VMove1Id");

                    b.HasIndex("VMove2Id");

                    b.HasIndex("VMove3Id");

                    b.HasIndex("VMove4Id");

                    b.HasIndex("VMove5Id");

                    b.HasIndex("XMove1Id");

                    b.HasIndex("XMove2Id");

                    b.HasIndex("XMove3Id");

                    b.HasIndex("XMove4Id");

                    b.HasIndex("XMove5Id");

                    b.HasIndex("ZMove1Id");

                    b.HasIndex("ZMove2Id");

                    b.HasIndex("ZMove3Id");

                    b.HasIndex("ZMove4Id");

                    b.HasIndex("ZMove5Id");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("MvcGame.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("Intellect")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("StyleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CBakiWebsite.Models.Style", b =>
                {
                    b.HasOne("CBakiWebsite.Models.Move", "BMove1")
                        .WithMany()
                        .HasForeignKey("BMove1Id");

                    b.HasOne("CBakiWebsite.Models.Move", "BMove2")
                        .WithMany()
                        .HasForeignKey("BMove2Id");

                    b.HasOne("CBakiWebsite.Models.Move", "BMove3")
                        .WithMany()
                        .HasForeignKey("BMove3Id");

                    b.HasOne("CBakiWebsite.Models.Move", "BMove4")
                        .WithMany()
                        .HasForeignKey("BMove4Id");

                    b.HasOne("CBakiWebsite.Models.Move", "BMove5")
                        .WithMany()
                        .HasForeignKey("BMove5Id");

                    b.HasOne("CBakiWebsite.Models.Move", "CMove1")
                        .WithMany()
                        .HasForeignKey("CMove1Id");

                    b.HasOne("CBakiWebsite.Models.Move", "CMove2")
                        .WithMany()
                        .HasForeignKey("CMove2Id");

                    b.HasOne("CBakiWebsite.Models.Move", "CMove3")
                        .WithMany()
                        .HasForeignKey("CMove3Id");

                    b.HasOne("CBakiWebsite.Models.Move", "CMove4")
                        .WithMany()
                        .HasForeignKey("CMove4Id");

                    b.HasOne("CBakiWebsite.Models.Move", "CMove5")
                        .WithMany()
                        .HasForeignKey("CMove5Id");

                    b.HasOne("CBakiWebsite.Models.Move", "MiscMove1")
                        .WithMany()
                        .HasForeignKey("MiscMove1Id");

                    b.HasOne("CBakiWebsite.Models.Move", "MiscMove2")
                        .WithMany()
                        .HasForeignKey("MiscMove2Id");

                    b.HasOne("CBakiWebsite.Models.Move", "MiscMove3")
                        .WithMany()
                        .HasForeignKey("MiscMove3Id");

                    b.HasOne("CBakiWebsite.Models.Move", "MiscMove4")
                        .WithMany()
                        .HasForeignKey("MiscMove4Id");

                    b.HasOne("CBakiWebsite.Models.Move", "MiscMove5")
                        .WithMany()
                        .HasForeignKey("MiscMove5Id");

                    b.HasOne("CBakiWebsite.Models.Move", "VMove1")
                        .WithMany()
                        .HasForeignKey("VMove1Id");

                    b.HasOne("CBakiWebsite.Models.Move", "VMove2")
                        .WithMany()
                        .HasForeignKey("VMove2Id");

                    b.HasOne("CBakiWebsite.Models.Move", "VMove3")
                        .WithMany()
                        .HasForeignKey("VMove3Id");

                    b.HasOne("CBakiWebsite.Models.Move", "VMove4")
                        .WithMany()
                        .HasForeignKey("VMove4Id");

                    b.HasOne("CBakiWebsite.Models.Move", "VMove5")
                        .WithMany()
                        .HasForeignKey("VMove5Id");

                    b.HasOne("CBakiWebsite.Models.Move", "XMove1")
                        .WithMany()
                        .HasForeignKey("XMove1Id");

                    b.HasOne("CBakiWebsite.Models.Move", "XMove2")
                        .WithMany()
                        .HasForeignKey("XMove2Id");

                    b.HasOne("CBakiWebsite.Models.Move", "XMove3")
                        .WithMany()
                        .HasForeignKey("XMove3Id");

                    b.HasOne("CBakiWebsite.Models.Move", "XMove4")
                        .WithMany()
                        .HasForeignKey("XMove4Id");

                    b.HasOne("CBakiWebsite.Models.Move", "XMove5")
                        .WithMany()
                        .HasForeignKey("XMove5Id");

                    b.HasOne("CBakiWebsite.Models.Move", "ZMove1")
                        .WithMany()
                        .HasForeignKey("ZMove1Id");

                    b.HasOne("CBakiWebsite.Models.Move", "ZMove2")
                        .WithMany()
                        .HasForeignKey("ZMove2Id");

                    b.HasOne("CBakiWebsite.Models.Move", "ZMove3")
                        .WithMany()
                        .HasForeignKey("ZMove3Id");

                    b.HasOne("CBakiWebsite.Models.Move", "ZMove4")
                        .WithMany()
                        .HasForeignKey("ZMove4Id");

                    b.HasOne("CBakiWebsite.Models.Move", "ZMove5")
                        .WithMany()
                        .HasForeignKey("ZMove5Id");

                    b.Navigation("BMove1");

                    b.Navigation("BMove2");

                    b.Navigation("BMove3");

                    b.Navigation("BMove4");

                    b.Navigation("BMove5");

                    b.Navigation("CMove1");

                    b.Navigation("CMove2");

                    b.Navigation("CMove3");

                    b.Navigation("CMove4");

                    b.Navigation("CMove5");

                    b.Navigation("MiscMove1");

                    b.Navigation("MiscMove2");

                    b.Navigation("MiscMove3");

                    b.Navigation("MiscMove4");

                    b.Navigation("MiscMove5");

                    b.Navigation("VMove1");

                    b.Navigation("VMove2");

                    b.Navigation("VMove3");

                    b.Navigation("VMove4");

                    b.Navigation("VMove5");

                    b.Navigation("XMove1");

                    b.Navigation("XMove2");

                    b.Navigation("XMove3");

                    b.Navigation("XMove4");

                    b.Navigation("XMove5");

                    b.Navigation("ZMove1");

                    b.Navigation("ZMove2");

                    b.Navigation("ZMove3");

                    b.Navigation("ZMove4");

                    b.Navigation("ZMove5");
                });

            modelBuilder.Entity("MvcGame.Models.Player", b =>
                {
                    b.HasOne("CBakiWebsite.Models.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Style");
                });
#pragma warning restore 612, 618
        }
    }
}
